### ISSUE TITLE
greasyfork上的脚本为啥删掉了？

### ISSUE THREAD

**Issue by jadonding** [zkytech/Tampermonkey_scripts#4]
如题，greasyfork上的脚本为啥删掉了？

**Comment by zkytech** [comment]
自己测了一下，脚本现在对新版页面还是无效的。暂时没时间仔细适配

**Comment by jadonding** [comment]
> 自己测了一下，脚本现在对新版页面还是无效的。暂时没时间仔细适配

我更新的这个版本应该能用吧

**Comment by zkytech** [comment]
比如[这个合集](https://www.bilibili.com/video/BV1D5411Y7mp/?spm_id_from=333.337.search-card.all.click&vd_source=5b7cf4daa7d98506767a0757e0b64d77)

测试无效。

chrome 106版本

**Comment by jadonding** [comment]
> 比如[这个合集](https://www.bilibili.com/video/BV1D5411Y7mp/?spm_id_from=333.337.search-card.all.click&vd_source=5b7cf4daa7d98506767a0757e0b64d77)
> 
> 测试无效。
> 
> chrome 106版本

设定目标的功能有问题，我都没注意，合集进度可以用。

**Comment by zkytech** [comment]
更新适配了，还有一些问题，刷新页面后有几率不生效。

**Comment by jadonding** [comment]
> 更新适配了，还有一些问题，刷新页面后有几率不生效。

你难道用的是旧版的页面？

**Comment by zkytech** [comment]
还真的是，我忘记切回来了。

**Comment by zkytech** [comment]
重新发布到greasyfork了
